name: BaseTemplate
on:
  workflow_call:
    secrets:
      password:
        required: true
    inputs:
      environment:
        required: true
        type: string
      username:
        required: true
        type: string
jobs:
  print:
    name: Print Username & Password
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Print String
        run: |
          echo "Username is ${{ vars.username }} and password is ${{ secrets.password }}"
