name: BaseTemplate
on:
  workflow_call:
    secrets:
      password:
        required: true
      token:
        required: true
    inputs:
      environment:
        required: true
        type: string
      username:
        required: true
        type: string
jobs:
  print:
    name: Print Username & Password
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Print String
        run: |
          echo "Username is ${{ inputs.username }} and password is ${{ secrets.password }} And token is ${{ secrets.token }}"

      - name: Dekh sappe
        env:
          USERNAME: ${{ inputs.username }}
          PASSWORD: ${{ secrets.password }}
          TOKEN: ${{ secrets.token }}
        run: |
          echo "Username is $USERNAME"
          echo "Password is $PASSWORD"
          echo "Token is $TOKEN"
        

