name: BaseTemplate
on:
  workflow_call:
    secrets:
      password:
        required: true
      token:
        required: true
    inputs:
      environment:
        required: true
        type: string
      username:
        required: true
        type: string

jobs:
  print:
    name: Print Username & Password
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Print Inputs and Secrets
        run: |
          echo "Inputs:"
          echo "Username: ${{ inputs.username }}"
          echo "Environment: ${{ inputs.environment }}"
          echo ""
          echo "Secrets:"
          echo "Password: ${{ secrets.password }}"
          echo "Token: ${{ secrets.token }}"

      - name: Debug with Env Variables
        run: |
          echo "Env Variables:"
          echo "Username is $USERNAME"
          echo "Password is $PASSWORD"
          echo "Token is $TOKEN"
        env:
          USERNAME: ${{ inputs.username }}
          PASSWORD: ${{ secrets.password }}
          TOKEN: ${{ secrets.token }}
