name: BaseTemplate
on:
  workflow_call:
    # secrets:
    #   password:
    #     required: true
    #   token:
    #     required: true
    inputs:
      environment:
        required: true
        type: string
      username:
        required: true
        type: string
      password:
        required: true
        type: string
      token:
        required: true
        type: string
jobs:
  print:
    name: Print Username & Password
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Print String
        run: |
          echo "Username is ${{ vars.username }} and password is ${{ secrets.password }} And token is ${{ secrets.token }}"
