name: BaseTemplate
on:
  workflow_call:
    # secrets:
    #   password:
    #     required: true
    #   token:
    #     required: true
    inputs:
      environment:
        required: true
        type: string

jobs:
  print:
    name: Print Username & Password
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Print Inputs and Secrets
        run: |
          echo "Inputs:"
          echo "Username: ${{ vars.user }}"
          echo "Environment: ${{ inputs.environment }}"
          echo ""
          echo "Secrets:"
          echo "Password: ${{ secrets.password }}"
          echo "Token: ${{ secrets.token }}"

      - name: Debug with Env Variables
        env:
          USERNAME: ${{ vars.user }}
          PASSWORD: ${{ secrets.password }}
          TOKEN: ${{ secrets.token }}
        run: |
          echo "Env Variables:"
          echo "Username: $USERNAME" > file1
          cat file1
          echo Password: $PASSWORD > file2
          cat file2
          echo "Token: $TOKEN" > file3
          cat file3
