# Workflow deployment template
name: print string Workflow
# Workflow trigger
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  dev:
    name: dev string print
    uses: saransh-10/environment-variable-test/.github/workflows/template.yml@main
    with:
      environment: dev
      username: ${{ vars.user }}
      password: ${{ secrets.password }}
      token: ${{ secrets.token }}
    # secrets: inherit
  uat:
    name: uat string print
    uses: saransh-10/environment-variable-test/.github/workflows/template.yml@main
    with:
      environment: uat
      username: ${{ vars.user }}
      password: ${{ secrets.password }}
      token: ${{ secrets.token }}
    # secrets: inherit
